FROM registry.access.redhat.com/ubi9/go-toolset:1.19

USER 0

ENV GOFLAGS=""
ENV GOPATH="/go"
ENV PATH="$PATH:$GOPATH/bin"

RUN dnf install -y 'dnf-command(config-manager)' && \
    dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo && \
    dnf install -y \
        docker-ce \
        docker-ce-cli \
        containerd.io \
        docker-compose-plugin \
    && dnf clean all

RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/bin v1.56.1
RUN go install golang.org/x/tools/cmd/goimports@v0.1.0 && \
    go install github.com/onsi/ginkgo/ginkgo@v1.16.1 && \
    go install github.com/golang/mock/mockgen@v1.6.0 && \
    go install github.com/vektra/mockery/v2@v2.9.6 && \
    go install gotest.tools/gotestsum@v1.6.3 && \
    go install github.com/axw/gocov/gocov@latest && \
    go install github.com/AlekSi/gocov-xml@latest
