FROM golang:1.13

RUN apt-get update ; apt-get install -y docker.io docker-compose
RUN go get -u github.com/onsi/ginkgo/ginkgo  # installs the ginkgo CLI
RUN go get -u github.com/onsi/gomega/...     # fetches the matcher library
RUN go get github.com/vektra/mockery/.../

