FROM golang:1.15.3
ENV GO111MODULE=on

RUN apt-get update ; apt-get install -y docker.io docker-compose
RUN go get -u golang.org/x/tools/cmd/goimports@v0.0.0-20200520220537-cf2d1e09c845 \
              github.com/onsi/ginkgo/ginkgo@v1.12.2  \
              github.com/golang/mock/mockgen@v1.4.3  \
              github.com/vektra/mockery/.../@v1.1.2 \
              gotest.tools/gotestsum@v0.5.3 \
              github.com/axw/gocov/gocov \
              github.com/AlekSi/gocov-xml@v0.0.0-20190121064608-3a14fb1c4737
