FROM registry.fedoraproject.org/fedora-minimal:latest
RUN microdnf install dmidecode ipmitool lshw biosdevname kmod systemd findutils && microdnf clean all
ADD build/inventory /usr/bin/inventory
CMD ["/usr/bin/inventory"]
