FROM --platform=$BUILDPLATFORM registry.access.redhat.com/ubi9/go-toolset:1.25 AS builder
ARG TARGETPLATFORM

ENV USER_UID=1001 \
    USER_NAME=assisted-installer

ENV COMPONENT_NAME=assisted-installer-agent
ENV COMPONENT_VERSION=1.0.0
ENV COMPONENT_TAG_EXTENSION=" "
ENV GOFLAGS="-p=4"

COPY --chown=${USER_UID} . /app
WORKDIR /app
RUN make build


FROM --platform=$BUILDPLATFORM registry.access.redhat.com/ubi9/ubi-minimal:latest@sha256:759f5f42d9d6ce2a705e290b7fc549e2d2cd39312c4fa345f93c02e4abb8da95

ARG release=main
ARG version=latest

COPY LICENSE /licenses/
COPY --from=builder /app/build/agent /usr/bin/agent

# The step binaries are all just symlinks to /usr/bin/agent
RUN ln -s /usr/bin/agent /usr/bin/free_addresses && \
    ln -s /usr/bin/agent /usr/bin/inventory && \
    ln -s /usr/bin/agent /usr/bin/logs_sender && \
    ln -s /usr/bin/agent /usr/bin/next_step_runner && \
    ln -s /usr/bin/agent /usr/bin/disk_speed_check

COPY --from=builder /app/scripts/installer/* /usr/local/bin/

# Install all packages using dnf for better dependency resolution with rpm-prefetching
RUN INSTALL_PKGS="findutils iputils podman ipmitool file sg3_utils fio nmap dhclient tar openssh-clients chrony util-linux hwdata kmod" && \
    X86_PKGS=$(if [ "$(uname -m)" == "x86_64" ]; then echo -n biosdevname dmidecode ; fi) && \
    ARM_PKGS=$(if [ "$(uname -m)" == "aarch64" ]; then echo -n dmidecode ; fi) && \
    PPC64LE_PKGS=$(if [ "$(uname -m)" == "ppc64le" ]; then echo -n '' ; fi) && \
    S390X_PKGS=$(if [ "$(uname -m)" == "s390x" ]; then echo -n '' ; fi) && \
    microdnf install -y dnf && \
    dnf upgrade -y --setopt=install_weak_deps=False --allowerasing openssl-libs pam && \
    dnf install -y --setopt=install_weak_deps=False --nobest --allowerasing $INSTALL_PKGS $X86_PKGS $ARM_PKGS $PPC64LE_PKGS $S390X_PKGS && \
    dnf clean all && \
    rm -rf /var/cache/{yum,dnf}/*

LABEL com.redhat.component="assisted-installer-agent-container" \
      name="rhai/assisted-installer-agent-rhel9" \
      cpe="cpe:/a:redhat:assisted_installer:2.38::el9" \
      version="${version}" \
      upstream-ref="${version}" \
      upstream-url="https://github.com/openshift/assisted-installer-agent.git" \
      url="https://github.com/openshift/assisted-installer-agent.git" \
      summary="OpenShift Assisted Installer Agent" \
      io.k8s.display-name="OpenShift Assisted Installer" \
      maintainer="Liat Gamliel <lgamliel@redhat.com>" \
      description="OpenShift Assisted Installer" \
      io.k8s.description="OpenShift Assisted Installer" \
      distribution-scope="public" \
      release="${release}" \
      vendor="Red Hat, Inc." \
      io.openshift.tags="OpenShift 4" \
      upstream_commit="${version}" \
      org.label-schema.vcs-ref="${version}" \
      org.label-schema.vcs-url="https://github.com/openshift/assisted-installer-agent"
