
FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.22-openshift-4.18 AS builder

WORKDIR /go/src/github.com/openshift/assisted-installer-agent
COPY . . 
RUN make build

FROM registry.ci.openshift.org/ocp/4.18:base-rhel9

LABEL io.openshift.release.operator=true

COPY --from=builder /go/src/github.com/openshift/assisted-installer-agent/build/agent /usr/bin/agent
RUN ln -s /usr/bin/agent /usr/bin/free_addresses && \
    ln -s /usr/bin/agent /usr/bin/inventory && \
    ln -s /usr/bin/agent /usr/bin/logs_sender && \
    ln -s /usr/bin/agent /usr/bin/next_step_runner && \
    ln -s /usr/bin/agent /usr/bin/disk_speed_check

RUN if [ "$(arch)" = "x86_64" ]; then dnf install -y biosdevname dmidecode; fi
RUN if [ "$(arch)" = "aarch64" ]; then dnf install -y dmidecode; fi
RUN dnf install -y dhclient file findutils fio ipmitool iputils nmap openssh-clients podman chrony sg3_utils && dnf clean all
