// Code generated by mockery v2.39.1. DO NOT EDIT.

package journalLogger

import (
	journald "github.com/ssgreg/journald"
	mock "github.com/stretchr/testify/mock"
)

// MockIJournalWriter is an autogenerated mock type for the IJournalWriter type
type MockIJournalWriter struct {
	mock.Mock
}

// Send provides a mock function with given fields: msg, p, fields
func (_m *MockIJournalWriter) Send(msg string, p journald.Priority, fields map[string]interface{}) error {
	ret := _m.Called(msg, p, fields)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, journald.Priority, map[string]interface{}) error); ok {
		r0 = rf(msg, p, fields)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockIJournalWriter creates a new instance of MockIJournalWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIJournalWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIJournalWriter {
	mock := &MockIJournalWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
