// Code generated by mockery v1.0.0. DO NOT EDIT.

package domain_resolution

import (
	net "net"

	mock "github.com/stretchr/testify/mock"
)

// MockDomainResolutionDependencies is an autogenerated mock type for the DomainResolutionDependencies type
type MockDomainResolutionDependencies struct {
	mock.Mock
}

// Resolve provides a mock function with given fields: domain
func (_m *MockDomainResolutionDependencies) Resolve(domain string) ([]net.IP, error) {
	ret := _m.Called(domain)

	var r0 []net.IP
	if rf, ok := ret.Get(0).(func(string) []net.IP); ok {
		r0 = rf(domain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]net.IP)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
